import { Client } from "@stomp/stompjs";
import { useCallback, useEffect, useState, type ChangeEvent, type FormEvent } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { ApiError, apiClient, uploadDocument, type SearchResponse } from "./api";
import { useAuth } from "./auth";
import type { Collection, Dashboard, Department, DirectPermission, Document, DocumentStatus, EffectivePermission, Page, Role, User } from "./types";
import { Dialog, Empty, Loading, Notice, PageTitle, Pager, Status, usePolling } from "./ui";

const formats = [".pdf", ".docx", ".txt", ".md"];
const date = (value: string | null | undefined) => value ? new Date(value).toLocaleString("ko-KR") : "—";
const allowedFile = (file: File) => file.size <= 50 * 1024 * 1024 && formats.some((type) => file.name.toLowerCase().endsWith(type));

export function LoginPage() {
  const { login } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState<Error>(); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setError(undefined); const form = new FormData(event.currentTarget); try { await login(String(form.get("email")), String(form.get("password"))); navigate("/search", { replace: true }); } catch (cause) { setError(cause); } finally { setBusy(false); } };
  return <main className="auth-page"><section className="auth-card"><p className="eyebrow">VectorShelf</p><h1>문서 지식관리</h1><p>계정으로 로그인하세요.</p>{error && <Notice error={error} />}<form onSubmit={submit}><label>이메일<input required name="email" type="email" autoComplete="email" /></label><label>비밀번호<input required name="password" type="password" autoComplete="current-password" /></label><button disabled={busy}>{busy ? "로그인 중…" : "로그인"}</button></form><p>계정이 없나요? <Link to="/signup">회원가입</Link></p></section></main>;
}

export function SignupPage() {
  const navigate = useNavigate(); const [departments, setDepartments] = useState<Department[]>(); const [error, setError] = useState<Error>(); const [busy, setBusy] = useState(false);
  const load = useCallback(() => apiClient.get<Department[]>("/departments", false).then((value) => setDepartments(value ?? [])).catch(setError), []); useEffect(() => { void load(); }, [load]);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setError(undefined); const form = new FormData(event.currentTarget); try { await apiClient.post("/auth/signup", { email: form.get("email"), password: form.get("password"), name: form.get("name"), departmentId: Number(form.get("departmentId")) }, false); navigate("/login", { replace: true }); } catch (cause) { setError(cause); } finally { setBusy(false); } };
  return <main className="auth-page"><section className="auth-card"><p className="eyebrow">VectorShelf</p><h1>회원가입</h1><p>가입 후 로그인해 주세요. 가입만으로 토큰이 발급되지는 않습니다.</p>{error && <Notice error={error} retry={load} />}{!departments ? <Loading /> : <form onSubmit={submit}><label>이름<input name="name" required autoComplete="name" /></label><label>이메일<input name="email" type="email" required autoComplete="email" /></label><label>비밀번호<input name="password" type="password" required minLength={12} maxLength={64} autoComplete="new-password" /><small>12~64자</small></label><label>부서<select name="departmentId" defaultValue="" required><option value="" disabled>부서를 선택하세요</option>{departments.filter((row) => row.status === "ACTIVE").map((row) => <option key={row.departmentId} value={row.departmentId}>{row.name}</option>)}</select></label><button disabled={busy}>{busy ? "가입 중…" : "가입"}</button></form>}<p><Link to="/login">로그인으로 돌아가기</Link></p></section></main>;
}

export function SearchPage() {
  const [result, setResult] = useState<SearchResponse>(); const [cache, setCache] = useState<string | null>(); const [error, setError] = useState<Error>(); const [advanced, setAdvanced] = useState(false); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setError(undefined); const form = new FormData(event.currentTarget); const flag = (name: string) => form.get(name) === "on"; try { const response = await apiClient.search({ query: String(form.get("query") || ""), search_mode: form.get("search_mode") || undefined, top_k: form.get("top_k") ? Number(form.get("top_k")) : undefined, hyde_enabled: flag("hyde_enabled"), reranking_enabled: flag("reranking_enabled"), multi_query_enabled: flag("multi_query_enabled"), generate_answer: flag("generate_answer") }); setResult(response.data); setCache(response.cache); } catch (cause) { setError(cause); } finally { setBusy(false); } };
  return <section><PageTitle title="검색">권한이 있는 문서 청크만 근거로 조회합니다.</PageTitle><form className="search-form" onSubmit={submit}><label className="sr-only" htmlFor="query">질문</label><textarea id="query" name="query" required rows={3} placeholder="문서에서 찾을 내용을 입력하세요" /><div className="row"><button type="button" className="secondary" onClick={() => setAdvanced(!advanced)} aria-expanded={advanced}>고급 옵션</button><button disabled={busy}>{busy ? "검색 중…" : "검색"}</button></div>{advanced && <fieldset className="advanced"><legend>실제 검색 요청 옵션</legend><label>검색 모드<select name="search_mode" defaultValue=""><option value="">서버 설정 사용</option><option value="hybrid">hybrid</option><option value="vector">vector</option><option value="keyword">keyword</option><option value="cascading">cascading</option></select></label><label>결과 수<input name="top_k" type="number" min="1" /></label><label><input name="hyde_enabled" type="checkbox" />HyDE 사용</label><label><input name="reranking_enabled" type="checkbox" />리랭킹 사용</label><label><input name="multi_query_enabled" type="checkbox" />다중 질의 사용</label><label><input name="generate_answer" type="checkbox" defaultChecked />답변 생성</label></fieldset>}</form>{error && <Notice error={error} />}{result && <SearchResults result={result} cache={cache} />}</section>;
}

export function SearchResults({ result, cache }: { result: SearchResponse; cache?: string | null }) {
  return <section className="search-results" aria-live="polite"><header><h2>검색 결과</h2>{cache && <span className="cache">캐시 {cache}</span>}</header>{result.answer && <article className="answer"><h3>답변</h3><p>{result.answer}</p></article>}<h3>근거 청크 ({result.results.length})</h3>{result.results.length === 0 ? <Empty>표시할 근거 청크가 없습니다.</Empty> : <ol className="evidence-list">{result.results.map((row, index) => <li key={row.chunk_id}><header><strong>근거 {index + 1}</strong><span>검색 점수: {row.score}</span></header><p>{row.content}</p><dl><dt>문서 ID</dt><dd>{row.document_id}</dd><dt>청크 ID</dt><dd>{row.chunk_id}</dd>{row.metadata && <><dt>메타데이터</dt><dd><pre>{JSON.stringify(row.metadata, null, 2)}</pre></dd></>}</dl></li>)}</ol>}</section>;
}

export function DocumentsPage() {
  const [page, setPage] = useState<Page<Document>>(); const [status, setStatus] = useState(""); const [error, setError] = useState<Error>(); const [upload, setUpload] = useState(false); const [notice, setNotice] = useState("");
  const load = useCallback((next = 0) => { const query = new URLSearchParams({ page: String(next), size: "20" }); if (status) query.set("status", status); apiClient.get<Page<Document>>(`/api/documents?${query}`).then(setPage).catch(setError); }, [status]); useEffect(() => { void load(); }, [load]);
  return <section><PageTitle title="문서" actions={<button onClick={() => setUpload(true)}>문서 업로드</button>}>상태 필터와 서버 페이지네이션을 사용합니다.</PageTitle>{notice && <p className="notice success" role="status">{notice}</p>}<label className="filter">상태<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">전체</option>{["DRAFT", "UPLOADED", "INDEXING", "INDEXED", "FAILED", "ARCHIVED", "DELETED"].map((value) => <option key={value}>{value}</option>)}</select></label>{error ? <Notice error={error} retry={() => load(page?.page ?? 0)} /> : !page ? <Loading /> : <><DocumentTable rows={page.content} /><Pager page={page} onPage={load} /></>}{upload && <UploadDialog onClose={() => setUpload(false)} onDone={() => { setUpload(false); setNotice("색인 접수 완료"); load(); }} />}</section>;
}

function DocumentTable({ rows }: { rows: Document[] }) { return rows.length === 0 ? <Empty>조건에 맞는 문서가 없습니다.</Empty> : <div className="table-wrap"><table><thead><tr><th>제목</th><th>상태</th><th>공개범위</th><th>현재 버전</th><th>수정</th></tr></thead><tbody>{rows.map((row) => <tr key={row.documentId}><td><Link to={`/documents/${row.documentId}`}>{row.title}</Link></td><td><Status value={row.status} /></td><td>{row.visibility}</td><td>{row.currentVersion ? `v${row.currentVersion.versionNo}` : "처리 중"}</td><td>{date(row.updatedAt)}</td></tr>)}</tbody></table></div>; }

function UploadDialog({ onClose, onDone, documentId }: { onClose: () => void; onDone: () => void; documentId?: number }) {
  const [file, setFile] = useState<File>(); const [error, setError] = useState<Error>(); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!file || !allowedFile(file)) { setError(new Error("PDF, DOCX, TXT, MD 파일이며 50 MiB 이하여야 합니다.")); return; } setBusy(true); setError(undefined); const form = new FormData(event.currentTarget); try { await uploadDocument(documentId ? `/api/documents/${documentId}/versions` : "/api/documents", { file, title: documentId ? undefined : String(form.get("title")), description: documentId ? undefined : String(form.get("description") || ""), visibility: documentId ? undefined : String(form.get("visibility")) }); onDone(); } catch (cause) { setError(cause); } finally { setBusy(false); } };
  return <Dialog title={documentId ? "새 버전 업로드" : "문서 업로드"} onClose={onClose}>{error && <Notice error={error} />}<form onSubmit={submit}><label>파일<input required type="file" accept={formats.join(",")} onChange={(event) => setFile(event.target.files?.[0])} /></label><small>PDF, DOCX, TXT, MD · 최대 50 MiB. 서버 검증이 최종 기준입니다.</small>{!documentId && <><label>제목<input name="title" required maxLength={500} /></label><label>설명<textarea name="description" /></label><label>공개범위<select name="visibility" defaultValue="PRIVATE"><option>PRIVATE</option><option>COLLECTION</option><option>DEPARTMENT</option><option>PUBLIC</option></select></label></>}<div className="dialog-actions"><button type="button" className="secondary" onClick={onClose}>취소</button><button disabled={busy}>{busy ? "업로드 중…" : "색인 접수"}</button></div></form></Dialog>;
}

export function DocumentDetailPage() {
  const id = Number(useParams().documentId); const { user } = useAuth(); const [document, setDocument] = useState<Document>(); const [state, setState] = useState<DocumentStatus>(); const [content, setContent] = useState<string>(); const [access, setAccess] = useState<EffectivePermission>(); const [error, setError] = useState<Error>(); const [edit, setEdit] = useState(false); const [version, setVersion] = useState(false); const [preview, setPreview] = useState<{ url: string; type: string }>();
  const load = useCallback(() => { Promise.all([apiClient.get<Document>(`/api/documents/${id}`), apiClient.get<DocumentStatus>(`/api/documents/${id}/status`), apiClient.get<EffectivePermission>(`/permissions/documents/${id}/me`)]).then(async ([detail, status, permission]) => { setDocument(detail); setState(status); setAccess(permission); if (detail?.contentAvailable) { try { setContent((await apiClient.get<{ content: string }>(`/api/documents/${id}/content`))?.content); } catch (cause) { if (!(cause instanceof ApiError) || cause.body.status !== 409) throw cause; } } }).catch(setError); }, [id]); useEffect(() => { void load(); }, [load]); usePolling(Boolean(state?.processingVersion), load, 5000); useEffect(() => () => { if (preview) URL.revokeObjectURL(preview.url); }, [preview]);
  const file = async (download: boolean) => { try { const received = await apiClient.blob(`/api/documents/${id}/file?disposition=${download ? "attachment" : "inline"}`); const url = URL.createObjectURL(received.blob); if (download) { const anchor = window.document.createElement("a"); anchor.href = url; anchor.download = received.filename || "document"; anchor.click(); URL.revokeObjectURL(url); } else { if (preview) URL.revokeObjectURL(preview.url); setPreview({ url, type: received.contentType }); } } catch (cause) { setError(cause); } };
  if (error) return <Notice error={error} retry={load} />; if (!document || !state) return <Loading />; const owner = user?.userId === document.ownerUserId;
  return <section><PageTitle title={document.title} actions={<><button className="secondary" onClick={() => file(false)}>원본 미리보기</button><button className="secondary" onClick={() => file(true)}>다운로드</button></>}>문서 ID {id}</PageTitle><div className="detail-grid"><article className="panel"><h2>문서 정보</h2><dl className="facts"><dt>상태</dt><dd><Status value={state.documentStatus} /></dd><dt>공개범위</dt><dd>{document.visibility}</dd><dt>소유자</dt><dd>{document.ownerName}</dd><dt>현재 버전</dt><dd>{document.currentVersion ? `v${document.currentVersion.versionNo}` : "없음"}</dd><dt>처리 중 버전</dt><dd>{state.processingVersion ? `v${state.processingVersion.versionNo} · ${state.processingVersion.jobStatus}` : "없음"}</dd><dt>설명</dt><dd>{document.description || "—"}</dd></dl>{access?.canWrite && <button onClick={() => setEdit(true)}>제목·설명 수정</button>}{owner && <><button onClick={() => setVersion(true)}>새 버전 업로드</button><Visibility documentId={id} value={document.visibility} done={load} /></>}{access?.canAdmin && <DeleteDocument id={id} />}</article><article className="panel"><h2>추출 본문</h2>{content ? <pre className="document-content">{content}</pre> : <Empty>{document.contentAvailable ? "본문을 불러올 수 없습니다." : "현재 추출 본문을 사용할 수 없습니다."}</Empty>}</article></div>{edit && <MetadataDialog document={document} close={() => setEdit(false)} done={() => { setEdit(false); load(); }} />}{version && <UploadDialog documentId={id} onClose={() => setVersion(false)} onDone={() => { setVersion(false); load(); }} />}{preview && <Dialog title="원본 미리보기" onClose={() => { URL.revokeObjectURL(preview.url); setPreview(undefined); }}>{preview.type === "application/pdf" || preview.type.startsWith("text/") ? <iframe className="preview" title="원본 문서" src={preview.url} /> : <p>이 형식은 브라우저 미리보기를 지원하지 않습니다. 다운로드해 확인하세요.</p>}</Dialog>}{access?.canAdmin && <PermissionPanel kind="documents" id={id} />}</section>;
}

function MetadataDialog({ document, close, done }: { document: Document; close: () => void; done: () => void }) { const [error, setError] = useState<Error>(); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await apiClient.patch(`/api/documents/${document.documentId}`, { title: String(form.get("title")), description: String(form.get("description") || "") || null }); done(); } catch (cause) { setError(cause); } }; return <Dialog title="문서 정보 수정" onClose={close}>{error && <Notice error={error} />}<form onSubmit={submit}><label>제목<input name="title" required defaultValue={document.title} maxLength={500} /></label><label>설명<textarea name="description" defaultValue={document.description || ""} /></label><div className="dialog-actions"><button type="button" className="secondary" onClick={close}>취소</button><button>저장</button></div></form></Dialog>; }
function Visibility({ documentId, value, done }: { documentId: number; value: string; done: () => void }) { const [error, setError] = useState<Error>(); const change = async (event: ChangeEvent<HTMLSelectElement>) => { try { await apiClient.patch(`/api/documents/${documentId}/visibility`, { visibility: event.target.value }); done(); } catch (cause) { setError(cause); } }; return <>{error && <Notice error={error} />}<label>공개범위 변경<select defaultValue={value} onChange={change}><option>PRIVATE</option><option>PUBLIC</option></select></label></>; }
function DeleteDocument({ id }: { id: number }) { const navigate = useNavigate(); const [error, setError] = useState<Error>(); const remove = async () => { if (!window.confirm("문서를 논리 삭제할까요?")) return; try { await apiClient.delete(`/api/documents/${id}`); navigate("/documents"); } catch (cause) { setError(cause); } }; return <>{error && <Notice error={error} />}<button className="danger" onClick={remove}>문서 삭제</button></>; }

export function CollectionsPage() {
  const [page, setPage] = useState<Page<Collection>>(); const [error, setError] = useState<Error>(); const [create, setCreate] = useState(false);
  const load = useCallback((next = 0) => apiClient.get<Page<Collection>>(`/collections?page=${next}&size=20`).then(setPage).catch(setError), []); useEffect(() => { void load(); }, [load]);
  return <section><PageTitle title="컬렉션" actions={<button onClick={() => setCreate(true)}>컬렉션 생성</button>}>이름 변경과 이동은 서버 API가 제공되지 않아 지원하지 않습니다.</PageTitle>{error ? <Notice error={error} retry={() => load(page?.page ?? 0)} /> : !page ? <Loading /> : page.content.length === 0 ? <Empty>접근 가능한 컬렉션이 없습니다.</Empty> : <><div className="table-wrap"><table><thead><tr><th>이름</th><th>공개범위</th><th>상위 ID</th><th>상태</th></tr></thead><tbody>{page.content.map((row) => <tr key={row.collectionId}><td><Link to={`/collections/${row.collectionId}`}>{row.name}</Link></td><td>{row.visibility}</td><td>{row.parentId ?? "—"}</td><td><Status value={row.status} /></td></tr>)}</tbody></table></div><Pager page={page} onPage={load} /></>}{create && <CollectionCreate close={() => setCreate(false)} done={() => { setCreate(false); load(); }} />}</section>;
}
function CollectionCreate({ close, done }: { close: () => void; done: () => void }) { const [error, setError] = useState<Error>(); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await apiClient.post("/collections", { name: form.get("name"), parentId: form.get("parentId") ? Number(form.get("parentId")) : null, visibility: form.get("visibility") }); done(); } catch (cause) { setError(cause); } }; return <Dialog title="컬렉션 생성" onClose={close}>{error && <Notice error={error} />}<form onSubmit={submit}><label>이름<input name="name" required /></label><label>상위 컬렉션 ID (선택)<input name="parentId" type="number" min="1" /></label><label>공개범위<select name="visibility" defaultValue="PRIVATE"><option>PRIVATE</option><option>COLLECTION</option><option>DEPARTMENT</option><option>PUBLIC</option></select></label><div className="dialog-actions"><button type="button" className="secondary" onClick={close}>취소</button><button>생성</button></div></form></Dialog>; }

export function CollectionDetailPage() {
  const id = Number(useParams().collectionId); const { user } = useAuth(); const [collection, setCollection] = useState<Collection>(); const [children, setChildren] = useState<Collection[]>(); const [documents, setDocuments] = useState<{ documentId: number }[]>(); const [error, setError] = useState<Error>(); const [add, setAdd] = useState(false);
  const load = useCallback(() => apiClient.get<Collection>(`/collections/${id}`).then(setCollection).catch(setError), [id]); useEffect(() => { void load(); }, [load]); const loadChildren = () => apiClient.get<Collection[]>(`/collections/${id}/children`).then((value) => setChildren(value ?? [])).catch(setError); const loadDocuments = () => apiClient.get<{ documentId: number }[]>(`/collections/${id}/documents`).then((value) => setDocuments(value ?? [])).catch(setError);
  if (error) return <Notice error={error} retry={load} />; if (!collection) return <Loading />; const owner = user?.userId === collection.ownerUserId;
  return <section><PageTitle title={collection.name}>컬렉션 ID {id}</PageTitle><section className="panel"><dl className="facts"><dt>공개범위</dt><dd>{collection.visibility}</dd><dt>상위 컬렉션</dt><dd>{collection.parentId ?? "없음"}</dd><dt>상태</dt><dd><Status value={collection.status} /></dd></dl>{owner && <CollectionControls id={id} value={collection.visibility} done={load} />}</section><div className="detail-grid"><section className="panel"><header className="section-heading"><h2>직계 자식</h2><button className="secondary" onClick={loadChildren}>불러오기</button></header>{children === undefined ? <Empty>요청 시에만 직계 자식을 불러옵니다.</Empty> : children.length ? <ul>{children.map((row) => <li key={row.collectionId}><Link to={`/collections/${row.collectionId}`}>{row.name}</Link></li>)}</ul> : <Empty>직계 자식이 없습니다.</Empty>}</section><section className="panel"><header className="section-heading"><h2>연결 문서</h2><span><button className="secondary" onClick={loadDocuments}>새로고침</button><button onClick={() => setAdd(true)}>문서 연결</button></span></header>{documents === undefined ? <Empty>문서 연결 목록을 불러오려면 새로고침을 선택하세요.</Empty> : documents.length ? <ul>{documents.map((row) => <li key={row.documentId}><Link to={`/documents/${row.documentId}`}>문서 {row.documentId}</Link>{owner && <button className="text-button danger-text" onClick={() => apiClient.delete(`/collections/${id}/documents/${row.documentId}`).then(loadDocuments).catch(setError)}>해제</button>}</li>)}</ul> : <Empty>연결된 문서가 없습니다.</Empty>}</section></div><PermissionPanel kind="collections" id={id} />{add && <DocumentAttach close={() => setAdd(false)} done={() => { setAdd(false); loadDocuments(); }} collectionId={id} />}</section>;
}
function CollectionControls({ id, value, done }: { id: number; value: string; done: () => void }) { const navigate = useNavigate(); const [error, setError] = useState<Error>(); const change = async (event: ChangeEvent<HTMLSelectElement>) => { try { await apiClient.patch(`/collections/${id}/visibility`, { visibility: event.target.value }); done(); } catch (cause) { setError(cause); } }; const remove = async () => { if (!window.confirm("이 컬렉션과 하위 컬렉션을 삭제할까요?")) return; try { await apiClient.delete(`/collections/${id}`); navigate("/collections"); } catch (cause) { setError(cause); } }; return <>{error && <Notice error={error} />}<label>공개범위 변경<select defaultValue={value} onChange={change}><option>PRIVATE</option><option>PUBLIC</option></select></label><button className="danger" onClick={remove}>컬렉션 삭제</button></>; }
function DocumentAttach({ collectionId, close, done }: { collectionId: number; close: () => void; done: () => void }) { const [error, setError] = useState<Error>(); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); try { await apiClient.post(`/collections/${collectionId}/documents`, { documentId: Number(new FormData(event.currentTarget).get("documentId")) }); done(); } catch (cause) { setError(cause); } }; return <Dialog title="문서 연결" onClose={close}>{error && <Notice error={error} />}<form onSubmit={submit}><label>문서 ID<input name="documentId" type="number" min="1" required /></label><p className="assist">문서 목록 키워드 검색 API가 없어 문서 ID를 사용합니다.</p><div className="dialog-actions"><button type="button" className="secondary" onClick={close}>취소</button><button>연결</button></div></form></Dialog>; }

function PermissionPanel({ kind, id }: { kind: "documents" | "collections"; id: number }) {
  const base = `/permissions/${kind}/${id}`; const [permissions, setPermissions] = useState<DirectPermission[]>(); const [error, setError] = useState<Error>(); const [allowed, setAllowed] = useState<boolean>(); const [target, setTarget] = useState("USER"); const [users, setUsers] = useState<User[]>([]); const [keyword, setKeyword] = useState(""); const [departments, setDepartments] = useState<Department[]>([]); const [roles, setRoles] = useState<Role[]>([]);
  const load = useCallback(() => apiClient.get<DirectPermission[]>(base).then((value) => { setPermissions(value ?? []); setAllowed(true); }).catch((cause) => { if (cause instanceof ApiError && cause.body.status === 403) setAllowed(false); else setError(cause); }), [base]); useEffect(() => { void load(); }, [load]); useEffect(() => { if (allowed) { apiClient.get<Department[]>("/departments", false).then((value) => setDepartments(value ?? [])).catch(() => undefined); apiClient.get<Role[]>("/roles").then((value) => setRoles(value ?? [])).catch(() => undefined); } }, [allowed]);
  const searchUsers = () => apiClient.get<User[]>(`${base}/users?keyword=${encodeURIComponent(keyword)}`).then((value) => setUsers(value ?? [])).catch(setError); const grant = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const body: Record<string, unknown> = { permissionKind: form.get("permissionKind"), targetType: target, expiresAt: form.get("expiresAt") || null }; if (target === "USER") body.userId = Number(form.get("userId")); if (target === "DEPARTMENT") body.departmentId = Number(form.get("departmentId")); if (target === "ROLE") body.roleCode = form.get("roleCode"); try { await apiClient.post(base, body); load(); } catch (cause) { setError(cause); } };
  if (allowed === false) return null; if (!permissions) return <section className="panel"><h2>직접 권한</h2><Loading /></section>;
  return <section className="panel permissions"><h2>직접 권한</h2>{error && <Notice error={error} retry={load} />}<ul>{permissions.length ? permissions.map((row) => <li key={row.permissionId}><span>{row.permissionKind} · {row.targetType} · {row.userId ?? row.departmentId ?? row.roleCode ?? "—"}</span><button className="text-button danger-text" onClick={() => apiClient.delete(`${base}/${row.permissionId}`).then(load).catch(setError)}>회수</button></li>) : <Empty>직접 부여된 권한이 없습니다.</Empty>}</ul><form className="permission-form" onSubmit={grant}><h3>권한 부여</h3><label>권한<select name="permissionKind"><option>READ</option><option>WRITE</option><option>ADMIN</option></select></label><label>대상<select value={target} onChange={(event) => setTarget(event.target.value)}><option>USER</option><option>DEPARTMENT</option><option>ROLE</option></select></label>{target === "USER" && <><div className="inline-form"><label>사용자 검색<input value={keyword} onChange={(event) => setKeyword(event.target.value)} maxLength={100} /></label><button type="button" className="secondary" onClick={searchUsers}>검색</button></div><label>사용자<select name="userId" required defaultValue=""><option value="" disabled>검색 후 선택</option>{users.map((row) => <option key={row.userId} value={row.userId}>{row.name} · {row.email}</option>)}</select></label></>}{target === "DEPARTMENT" && <label>부서<select name="departmentId">{departments.map((row) => <option key={row.departmentId} value={row.departmentId}>{row.name}</option>)}</select></label>}{target === "ROLE" && <label>역할<select name="roleCode">{roles.map((row) => <option key={row.code} value={row.code}>{row.name}</option>)}</select></label>}<label>만료 시각 (선택)<input name="expiresAt" type="datetime-local" /></label><button>권한 부여</button></form></section>;
}

type Token = { tokenId: string; createdAt: string; lastUsedAt: string | null; revokedAt: string | null };
export function McpKeysPage() {
  const [tokens, setTokens] = useState<Token[]>(); const [issued, setIssued] = useState<(Token & { apiKey: string })>(); const [error, setError] = useState<Error>(); const load = useCallback(() => apiClient.get<Token[]>("/mcp/tokens").then((value) => setTokens(value ?? [])).catch(setError), []); useEffect(() => { void load(); }, [load]);
  const issue = () => apiClient.post<Token & { apiKey: string }>("/mcp/tokens").then((value) => { if (value) { setIssued(value); load(); } }).catch(setError); const copy = async () => { if (issued) { await navigator.clipboard.writeText(issued.apiKey); setIssued(undefined); } };
  return <section><PageTitle title="MCP 키" actions={<button onClick={issue}>새 키 발급</button>}>원본 키는 발급 직후 한 번만 표시됩니다.</PageTitle>{error ? <Notice error={error} retry={load} /> : !tokens ? <Loading /> : tokens.length === 0 ? <Empty>발급한 MCP 키가 없습니다.</Empty> : <div className="table-wrap"><table><thead><tr><th>키 ID</th><th>발급</th><th>마지막 사용</th><th>상태</th><th /></tr></thead><tbody>{tokens.map((row) => <tr key={row.tokenId}><td>{row.tokenId}</td><td>{date(row.createdAt)}</td><td>{date(row.lastUsedAt)}</td><td><Status value={row.revokedAt ? "REVOKED" : "ACTIVE"} /></td><td>{!row.revokedAt && <button className="text-button danger-text" onClick={() => apiClient.delete(`/mcp/tokens/${row.tokenId}`).then(load).catch(setError)}>폐기</button>}</td></tr>)}</tbody></table></div>}{issued && <Dialog title="새 MCP 키" onClose={() => setIssued(undefined)}><p>지금 복사하지 않으면 다시 볼 수 없습니다.</p><textarea aria-label="새 MCP 키" readOnly rows={3} value={issued.apiKey} /><div className="dialog-actions"><button onClick={copy}>복사하고 닫기</button></div></Dialog>}</section>;
}

export function DashboardPage() {
  const [summary, setSummary] = useState<Dashboard>(); const [error, setError] = useState<Error>(); const [live, setLive] = useState("연결 준비 중"); const load = useCallback(() => apiClient.get<Dashboard>("/admin/dashboard/summary").then(setSummary).catch(setError), []);
  useEffect(() => { let timer: number | undefined; let client: Client | undefined; let closed = false; const fallback = (message: string) => { setLive(message); if (!timer) timer = window.setInterval(load, 30000); }; const connect = async () => { await load(); if (closed) return; const token = sessionStorage.getItem("vectorshelf.jwt"); if (!token) return; client = new Client({ brokerURL: `${window.location.protocol === "https:" ? "wss" : "ws"}://${window.location.host}/ws`, connectHeaders: { Authorization: `Bearer ${token}` }, reconnectDelay: 0, onConnect: () => { setLive("실시간 연결됨"); client?.subscribe("/topic/dashboard", load); }, onWebSocketError: () => fallback("실시간 연결 실패 — 30초 폴링 중"), onStompError: () => fallback("실시간 인증 실패 — 30초 폴링 중") }); client.activate(); }; void connect(); return () => { closed = true; void client?.deactivate(); if (timer) clearInterval(timer); }; }, [load]);
  if (error) return <Notice error={error} retry={load} />; if (!summary) return <Loading />; const cards = [["전체 문서", summary.documents.total], ["검색 가능", summary.documents.searchable], ["색인 대기", summary.documents.pendingIndex], ["대기 작업", summary.jobs.pending], ["처리 작업", summary.jobs.processing], ["실패 작업", summary.jobs.failed], ["평균 처리", summary.jobs.avgProcessMs === null ? "—" : `${Math.round(summary.jobs.avgProcessMs)}ms`], ["활성 Worker", `${summary.workers.activeCount} / ${summary.workers.totalCount}`], ["최근 24시간 검색", summary.search.recent24hCount]];
  return <section><PageTitle title="운영">{live}</PageTitle><div className="metrics">{cards.map(([label, value]) => <article className="metric" key={String(label)}><p>{label}</p><strong>{value}</strong></article>)}</div></section>;
}

type Job = { jobId: number; documentId: number; status: string; retryCount: number; maxRetries: number; [key: string]: unknown };
export function JobsPage() {
  const [page, setPage] = useState<Page<Job>>(); const [filter, setFilter] = useState(""); const [selected, setSelected] = useState<Job>(); const [attempts, setAttempts] = useState<Record<string, unknown>[]>(); const [events, setEvents] = useState<Record<string, unknown>[]>(); const [workers, setWorkers] = useState<Record<string, unknown>[]>(); const [error, setError] = useState<Error>();
  const load = useCallback((next = 0) => { const query = new URLSearchParams({ page: String(next), size: "20" }); if (filter) query.set("status", filter); apiClient.get<Page<Job>>(`/admin/indexing-jobs?${query}`).then(setPage).catch(setError); apiClient.get<Record<string, unknown>[]>("/admin/workers").then((value) => setWorkers(value ?? [])).catch(() => undefined); }, [filter]); useEffect(() => { void load(); }, [load]); const detail = (job: Job) => Promise.all([apiClient.get<Job>(`/admin/indexing-jobs/${job.jobId}`), apiClient.get<Record<string, unknown>[]>(`/admin/indexing-jobs/${job.jobId}/attempts`), apiClient.get<Record<string, unknown>[]>(`/admin/indexing-jobs/${job.jobId}/events`)]).then(([row, a, e]) => { setSelected(row); setAttempts(a ?? []); setEvents(e ?? []); }).catch(setError);
  return <section><PageTitle title="색인 작업">Worker의 claim·lease·attempt·chunk·embedding·complete·fail은 사람이 실행하지 않습니다.</PageTitle><label className="filter">상태<select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="">전체</option>{["PENDING", "PROCESSING", "INDEXED", "FAILED"].map((value) => <option key={value}>{value}</option>)}</select></label>{error && <Notice error={error} retry={() => load(page?.page ?? 0)} />}{!page ? <Loading /> : <><div className="table-wrap"><table><thead><tr><th>작업</th><th>문서</th><th>상태</th><th>시도</th><th /></tr></thead><tbody>{page.content.map((row) => <tr key={row.jobId}><td>{row.jobId}</td><td>{row.documentId}</td><td><Status value={row.status} /></td><td>{row.retryCount} / {row.maxRetries}</td><td><button className="secondary" onClick={() => detail(row)}>상세</button></td></tr>)}</tbody></table></div><Pager page={page} onPage={load} /></>}{selected && <section className="panel"><h2>작업 {selected.jobId}</h2><DataList rows={[selected]} />{selected.status === "FAILED" && <button onClick={() => apiClient.post(`/admin/indexing-jobs/${selected.jobId}/retry`).then(() => { detail(selected); load(); }).catch(setError)}>실패 작업 재시도</button>}<h3>시도</h3><DataList rows={attempts} /><h3>이벤트</h3><DataList rows={events} /></section>}<section className="panel"><h2>Worker</h2><DataList rows={workers} /></section></section>;
}
function DataList({ rows }: { rows: Record<string, unknown>[] | undefined }) { return !rows ? <Loading /> : rows.length === 0 ? <Empty>항목이 없습니다.</Empty> : <div className="table-wrap"><table><tbody>{rows.map((row, index) => <tr key={String(row.eventId ?? row.attemptId ?? row.workerId ?? row.jobId ?? index)}>{Object.entries(row).map(([key, value]) => <td key={key}><small>{key}</small><br />{String(value ?? "—")}</td>)}</tr>)}</tbody></table></div>; }

type SyncRows = Page<Record<string, unknown>>;
export function SyncPage() {
  const [summary, setSummary] = useState<Record<string, unknown>>(); const [events, setEvents] = useState<SyncRows>(); const [issues, setIssues] = useState<SyncRows>(); const [error, setError] = useState<Error>(); const [ignore, setIgnore] = useState<string>();
  const load = useCallback(() => Promise.all([apiClient.get<Record<string, unknown>>("/admin/sync/summary"), apiClient.get<SyncRows>("/admin/sync/events?page=0&size=20"), apiClient.get<SyncRows>("/admin/sync/issues?page=0&size=20")]).then(([one, two, three]) => { setSummary(one); setEvents(two); setIssues(three); }).catch(setError), []); useEffect(() => { void load(); }, [load]); const action = (path: string, body?: Record<string, unknown>) => apiClient.post(path, body).then(() => { setIgnore(undefined); load(); }).catch(setError);
  return <section><PageTitle title="동기화">실제 지원되는 retry, repair, ignore, reconcile만 제공합니다.</PageTitle>{error && <Notice error={error} retry={load} />}{!summary || !events || !issues ? <Loading /> : <><section className="panel"><h2>요약</h2><DataList rows={[summary]} /><button className="secondary" onClick={() => action("/admin/sync/reconcile", { mode: "DRY_RUN" })}>정합성 검사</button><button onClick={() => action("/admin/sync/reconcile", { mode: "REPAIR" })}>정합성 복구 실행</button></section><section className="panel"><h2>이벤트</h2><DataList rows={events.content} />{events.content.filter((row) => row.status === "FAILED").map((row) => <button key={String(row.eventId)} className="secondary" onClick={() => action(`/admin/sync/events/${row.eventId}/retry`)}>이벤트 재시도</button>)}</section><section className="panel"><h2>이슈</h2><DataList rows={issues.content} />{issues.content.map((row) => <div className="row" key={String(row.issueId)}>{row.status !== "RESOLVED" && <button className="secondary" onClick={() => action(`/admin/sync/issues/${row.issueId}/repair`)}>복구</button>}{row.status === "OPEN" && <button className="text-button danger-text" onClick={() => setIgnore(String(row.issueId))}>무시</button>}</div>)}</section></>}{ignore && <Dialog title="동기화 이슈 무시" onClose={() => setIgnore(undefined)}><form onSubmit={(event) => { event.preventDefault(); const reason = String(new FormData(event.currentTarget).get("reason") || "").trim(); if (reason) action(`/admin/sync/issues/${ignore}/ignore`, { reason }); }}><label>무시 사유<textarea name="reason" required /></label><p className="assist">사유 입력은 필수입니다.</p><div className="dialog-actions"><button type="button" className="secondary" onClick={() => setIgnore(undefined)}>취소</button><button className="danger">무시</button></div></form></Dialog>}</section>;
}

export function UsersPage() {
  const [users, setUsers] = useState<User[]>(); const [roles, setRoles] = useState<Role[]>(); const [departments, setDepartments] = useState<Department[]>(); const [error, setError] = useState<Error>(); const load = useCallback(() => Promise.all([apiClient.get<User[]>("/admin/users"), apiClient.get<Role[]>("/roles"), apiClient.get<Department[]>("/departments", false)]).then(([one, two, three]) => { setUsers(one ?? []); setRoles(two ?? []); setDepartments(three ?? []); }).catch(setError), []); useEffect(() => { void load(); }, [load]); const change = (path: string, method: "POST" | "PATCH" | "DELETE", body?: Record<string, unknown>) => { const request = method === "DELETE" ? apiClient.delete(path) : method === "PATCH" ? apiClient.patch(path, body ?? {}) : apiClient.post(path, body); request.then(load).catch(setError); };
  return <section><PageTitle title="사용자 관리">역할 부여·회수와 부서 변경만 지원합니다.</PageTitle>{error && <Notice error={error} retry={load} />}{!users || !roles || !departments ? <Loading /> : users.length === 0 ? <Empty>사용자가 없습니다.</Empty> : <div className="user-list">{users.map((user) => <article className="panel" key={user.userId}><h2>{user.name} <small>{user.email}</small></h2><label>부서 변경<select value={user.departmentId ?? ""} onChange={(event) => change(`/admin/users/${user.userId}/department`, "PATCH", { departmentId: Number(event.target.value) })}>{departments.filter((row) => row.status === "ACTIVE").map((row) => <option key={row.departmentId} value={row.departmentId}>{row.name}</option>)}</select></label><h3>역할</h3><ul className="inline-list">{user.roles.map((role) => <li key={role}>{role}<button className="text-button danger-text" onClick={() => change(`/admin/users/${user.userId}/roles/${encodeURIComponent(role)}`, "DELETE")}>회수</button></li>)}</ul><label>역할 부여<select defaultValue="" onChange={(event) => { if (event.target.value) { change(`/admin/users/${user.userId}/roles`, "POST", { roleCode: event.target.value }); event.currentTarget.value = ""; } }}><option value="" disabled>역할 선택</option>{roles.filter((role) => !user.roles.includes(role.code)).map((role) => <option key={role.code} value={role.code}>{role.name}</option>)}</select></label></article>)}</div>}</section>;
}
